/*
Copyright 2026 The Kubernetes resource-state-metrics Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/utils/strings/slices"
)

const (

	// ConditionTypeProcessed represents the condition type for a resource that has been processed successfully.
	ConditionTypeProcessed = iota

	// ConditionTypeFailed represents the condition type for resource that has failed to process further.
	ConditionTypeFailed

	// ConditionTypeCardinalityWarning represents the condition type when cardinality reaches warning threshold (80% default).
	ConditionTypeCardinalityWarning

	// ConditionTypeCardinalityCutoff represents the condition type when cardinality exceeds hard threshold (100%).
	ConditionTypeCardinalityCutoff
)

var (

	// ConditionType is a slice of strings representing the condition types.
	ConditionType = []string{"Processed", "Failed", "CardinalityWarning", "CardinalityCutoff"}

	// ConditionMessageTrue is a group of condition messages applicable when the associated condition status is true.
	ConditionMessageTrue = []string{
		"Resource configuration has been processed successfully",
		"Resource failed to process",
		"Cardinality is approaching threshold",
		"Cardinality threshold exceeded, metric generation cut off",
	}

	// ConditionMessageFalse is a group of condition messages applicable when the associated condition status is false.
	ConditionMessageFalse = []string{
		"Resource configuration is yet to be processed",
		"N/A",
		"Cardinality is within acceptable limits",
		"Cardinality is within acceptable limits",
	}

	// ConditionReasonTrue is a group of condition reasons applicable when the associated condition status is true.
	ConditionReasonTrue = []string{"EventHandlerSucceeded", "EventHandlerFailed", "CardinalityWarning", "CardinalityCutoff"}

	// ConditionReasonFalse is a group of condition reasons applicable when the associated condition status is false.
	ConditionReasonFalse = []string{"EventHandlerRunning", "N/A", "CardinalityOK", "CardinalityOK"}
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:resource:singular=resourcemetricsmonitor,scope=Namespaced,shortName=rmm
// +kubebuilder:rbac:groups=resource-state-metrics.instrumentation.k8s-sigs.io,resources=resourcemetricsmonitors;resourcemetricsmonitors/status,verbs=*
// +kubebuilder:rbac:groups=apiextensions.k8s.io,resources=customresourcedefinitions,verbs=get;list;watch
// +kubebuilder:rbac:groups=authentication.k8s.io,resources=tokenreviews,verbs=create
// +kubebuilder:rbac:groups=authorization.k8s.io,resources=subjectaccessreviews,verbs=create
// +kubebuilder:subresource:status

// ResourceMetricsMonitor is a specification for a ResourceMetricsMonitor resource.
type ResourceMetricsMonitor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ResourceMetricsMonitorSpec   `json:"spec"`
	Status            ResourceMetricsMonitorStatus `json:"status,omitempty"`
}

// ResourceMetricsMonitorSpec is the spec for a ResourceMetricsMonitor resource.
type ResourceMetricsMonitorSpec struct {

	// +kubebuilder:validation:Required
	// +required

	// Configuration is the RSM configuration that generates metrics.
	Configuration string `json:"configuration"`
}

// +kubebuilder:validation:Optional
// +optional

// ResourceMetricsMonitorStatus is the status for a ResourceMetricsMonitor resource.
type ResourceMetricsMonitorStatus struct {

	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type

	// Conditions is an array of conditions associated with the resource.
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// Cardinality tracks the cardinality metrics for this resource.
	Cardinality *CardinalityStatus `json:"cardinality,omitempty"`
}

// CardinalityStatus tracks cardinality information for the RMM resource.
type CardinalityStatus struct {
	// Total is the total number of time series generated by this RMM.
	Total int64 `json:"total"`

	// PerStore maps store identifiers (group/version/kind) to their cardinality.
	PerStore map[string]int64 `json:"perStore,omitempty"`

	// PerFamily maps family names to their cardinality.
	PerFamily map[string]int64 `json:"perFamily,omitempty"`

	// ThresholdsExceeded indicates whether any cardinality threshold has been exceeded.
	ThresholdsExceeded bool `json:"thresholdsExceeded"`

	// CutoffFamilies lists the families that are currently cut off due to threshold violations.
	CutoffFamilies []string `json:"cutoffFamilies,omitempty"`

	// LastUpdated is the timestamp of the last cardinality update.
	LastUpdated metav1.Time `json:"lastUpdated"`
}

// Set sets the given condition for the resource.
func (status *ResourceMetricsMonitorStatus) Set(
	resource *ResourceMetricsMonitor,
	condition metav1.Condition,
) {
	// Prefix condition messages with consistent hints.
	var message, reason string
	conditionTypeNumeric := slices.Index(ConditionType, condition.Type)
	if condition.Status == metav1.ConditionTrue {
		reason = ConditionReasonTrue[conditionTypeNumeric]
		message = ConditionMessageTrue[conditionTypeNumeric]
	} else {
		reason = ConditionReasonFalse[conditionTypeNumeric]
		message = ConditionMessageFalse[conditionTypeNumeric]
	}

	// Populate status fields.
	condition.Reason = reason
	condition.Message = message
	condition.LastTransitionTime = metav1.Now()
	condition.ObservedGeneration = resource.GetGeneration()

	// Check if the condition already exists.
	for i, existingCondition := range status.Conditions {
		if existingCondition.Type == condition.Type {
			// Update the existing condition.
			status.Conditions[i] = condition

			return
		}
	}

	// Append the new condition if it does not exist (+listMapKey=type).
	status.Conditions = append(status.Conditions, condition)
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

// ResourceMetricsMonitorList is a list of ResourceMetricsMonitor resources.
type ResourceMetricsMonitorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []ResourceMetricsMonitor `json:"items"`
}
